[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/assets/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
